# Generated by Django 2.2.16 on 2022-12-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_textmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextModel',
        ),
    ]
